config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/page'
  root 'home#page'
  resources :photos
  get 'portfolio', to: 'photos#portfolio'
  get 'home/help'
  resources :transactions, only: [:create]
  get 'checkout/success', to: 'transactions#success'
  post '/transactions/webhook', to: 'transactions#webhook'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
    validates :title, :image, :price, presence: true
    has_one_attached :image
    belongs_to :user
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :seller, class_name: "User"
  belongs_to :buyer, class_name: "User"
  belongs_to :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :photos

  has_many :sales, class_name: "Transaction", foreign_key: :seller_id
  has_many :sold_photos, through: :sales, source: :photo

  has_many :purchases, class_name: "Transaction", foreign_key: :buyer_id
  has_many :purchased_photos, through: :purchases, source: :photo

  scope :sellers, -> { joins(:sales) }
  scope :buyers, -> { joins(:purchases) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # Query to select the 6 most recently added photos for display on home page, based on datestamp in db
  def page
    @photos = Photo.order(:created_at).reverse_order.limit(6)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    before_action :set_photo, only: %i[ show edit update destroy ]
    before_action :authenticate_user!, only: %i[ new create edit update destroy ]
    rescue_from Pundit::NotAuthorizedError, with: :unauthorised 

    # Alert message if user attempts to edit or delete another users image
    def unauthorised
        flash[:alert] = "Sorry! You do not have access to do that. If you believe this is an error, please report the issue via the help page."
        redirect_to photos_path
    end
    # Method to list all photos 
    # Added query to display most recently added photos first 
    def index
        @photos = Photo.order(:created_at).reverse_order
    end 
 
    # Need to include although there is no method defined - needed for view to retrieve form    
    def show
    end

    # Added Pundit authorisation so users can only edit their own photos
    def edit
        authorize @photo
    end

    # Query to only display photos uploaded by the current user for their portfolio
    def portfolio
        if user_signed_in?
        @portfolio = Photo.where(user_id: current_user.id)
        else   
        end
    end

    # To create new instance of the photo model
    def new
        @photo = Photo.new 
    end

    # Create method creates new instance, saves it and informs user
    def create
        # raise params.inspect
        @photo = Photo.new(photo_params)

        respond_to do |format|
        if @photo.save
            format.html { redirect_to @photo, notice: "Photo was successfully created." }
            format.json { render :show, status: :created, location: @photo }
        else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @photo.errors, status: :unprocessable_entity }
        end
        end
    end

    # To update photo listing  
    def update
        respond_to do |format|
            if @photo.update(photo_params)
            format.html { redirect_to @photo, notice: "Photo listing has been successfully updated." }
            format.json { render :show, status: :ok, location: @photo }
            else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @photo.errors, status: :unprocessable_entity }
            end
        end
    end

    # To delete an instance of a photo listing 
    def destroy
        authorize @photo
        @photo.destroy
        respond_to do |format|
            format.html { redirect_to photos_url, notice: "Photo listing has been successfully deleted." }
            format.json { head :no_content }
        end
    end

    # Private methods 
    private

    # Set used to find instance to edit or delete 
    def set_photo
        @photo = Photo.find(params[:id])
    end

    # List all trusted params in symbol format (e.g. :name, :description, :price)
    # Get this info from db migration or schema file (or ERD)
    # Any arrays need to be listed at the end
    def photo_params
        params.require(:photo).permit(:title, :description, :price, :category, :style, :image).merge(user_id: current_user.id)
    end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:create, :webhook]

    # Stripe payment checkout session, automatically downloads image if payment is successful
    def create
        photo = Photo.find params["id"]
        session = Stripe::Checkout::Session.create({
            payment_method_types: ['card'],
            line_items: [
               {
                price_data: {
                    unit_amount: photo.price*100,
                    currency: 'aud',
                    product_data: {
                        name: photo.title
                    },
                },
                quantity: 1,
            }],
            mode: 'payment',
            success_url: rails_blob_url(photo.image, disposition: "attachment"),
            cancel_url: photos_url,
        })
        render json: { id: session.id }

    end

    # Webhook set up through Ultrahook to track if checkout session was completed. Results an be accessed through Stripe dashboard.
    def webhook
        transaction_id= params[:data][:object][:payment_intent]
        transaction = Stripe::PaymentIntent.retrieve(transaction_id)
        photo_id = transaction.metadata.photo_id
        user_id = transaction.metadata.user_id
        render plain: "Success"
    end

    def transaction_params
        params.require(:transaction).permit(:id, :seller_id, :buyer_id, :photo_id, :amount, :photo)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/home/help.html.erb
<h2 class="page_title">Thank you for using Pixeltastic!</h2>

<section class="help_text">
    <p>Pixeltastic has been created to let creative photographers showcase and sell their work at a price of their choosing.</p>

    <p>You can browse the images for sale on Pixeltastic without creating an account. If you would like to buy any photos or sell your own photos you will need to set up an account.</p>

    <p>If you have any issues editing or deleting any of your photo listings, please double check you are logged in.</p>

    <p>If you need to reset your password, please visit </p>
    <button type="button" class="btn btn-primary">
        <%= link_to 'Password Reset', new_user_password_path %>
    </button>

    <br>
    <br>

    <p>If you need to report an issue, please visit:</p>
    <button type="button" class="btn btn-primary">
        <a href="https://github.com/katherine-rock/pixeltastic/issues" target="_blank">https://github.com/katherine-rock/pixeltastic/issues</a>
    </button>
    <p></p>
</section>

app/views/home/page.html.erb
<section class="welcome">
    <h2>Welcome to Pixeltastic!</h2>
    <h4>An easy to use, stock photography website to buy and sell creative photographs.</h4>
    <br>
    <p>Here are the latest additions to our collection.</p>
</section>

<section class="main">
    <% @photos.each do | photo | %>
        <div class="card" style="width: 18rem;">
        <%= image_tag photo.image, class: "card-img-top" %>

        <div class="card-body">
            <strong>Title: </strong><%= photo.title %>
            <br>
            <% if photo.category? %>
            <strong>Category: </strong><%= photo.category %>
            <% else %>
            <&nbsp;;>
            <% end %>
            <br>
            <strong>Price: $</strong><%= photo.price %>
            <br>

        <button type="button" class="btn btn-primary">
            <%= link_to 'Learn More', photo %>
        </button>

        </div>
        </div>  
    <% end %>  
</section>

<div class="button_view_all">
    <button type="button" class="btn btn-warning">
        <%= link_to 'View More Photos', photos_path %>
    </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pixeltastic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('camera_favicon.png') %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
    <%= render 'shared/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= yield %>
    <%= render 'shared/navbar' %>
  </body>
</html>

app/views/photos/_form.html.erb
<section class="upload_form">
  <%= form_with(model: photo) do |form| %>
    <% if photo.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

        <ul>
          <% photo.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :image %><%= "*"%>
      <%= form.file_field :image, accept: 'image/png, image/jpg, image/jpeg, image/webp' %>
    </div>

    <div class="field">
      <%= form.label :title %><%= "*"%>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

    <div class="field">
      <%= form.label :price %><%= "*"%>
      <%= form.number_field :price, in: 1..99999 %>
    </div>

    <div class="field">
      <%= form.label :category %>
      <%= form.select :category,
      %w( Landscape Wildlife Nature Architecture Portrait Travel Other) %>
    </div>

    <div class="field">
      <%= form.label :style %>
      <%= form.select :style,
     ["Colour", "Black & White" ] %>
    </div>

    <br>

    <div class="actions upload_button">
      <%= form.submit %>
    </div>

    <br>

  <% end %>

</section>

app/views/photos/edit.html.erb
<h1 class="page_title">Edit Your Photo</h1>

<%= render 'form', photo: @photo %>

<section class="grouped_buttons">
    <button type="button" class="btn btn-info">
        <%= link_to 'Show', @photo %> 
    </button >

    <button type="button" class="btn btn-info">
        <%= link_to 'Back', photos_path %> 
    </button>
</section>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="page_title">Image Catalogue</h1>

<section class="main">
  <% @photos.each do | photo | %> 
  <div class="card" style="width: 18rem;">

      <%= image_tag photo.image, class: "card-img-top" %>

      <div class="card-body">
        <strong>Title: </strong><%= sanitize(photo.title) %>
        <br>
        <% if photo.category? %>
        <strong>Category: </strong><%= photo.category %>
        <% else %>
        <&nbsp;;>
        <% end %>
        <br>
        <strong>Price: $</strong><%= photo.price %>
        <br>

      <button type="button" class="btn btn-primary">
        <%= link_to 'Learn More', photo %>
      </button>

      <% if user_signed_in? %>
        <% if photo.user_id == current_user.id %>
            <button type="button" class="btn btn-primary">
              <%= link_to 'Edit', edit_photo_path(photo) %>
            </button>
          
            <button type="button" class="btn btn-primary">
              <%= link_to 'Delete', photo, method: :delete, data: { confirm: 'Are you sure? This action is permanent.' } %>
            </button>
        <% end %>
      <% end %>
      </div>
  </div>

  <% end %>
</section>

app/views/photos/new.html.erb
<p></p>
<h1 class="page_title">Upload a New Photo</h1>

<%= render 'form', photo: @photo %>

<button type="button" class="btn btn-info back_button">
    <%= link_to 'Back', photos_path %>
</button>

app/views/photos/portfolio.html.erb
<h1 class="page_title">Portfolio</h1>

<section class="portfolio_text">

    <% if !user_signed_in? %>
        <p>You need to be logged in to view your portfolio. Please log in or sign up below.</p>
        <button type="button" class="btn btn-primary">
            <%= link_to 'Log In', new_user_session_path %>
        </button>

        <button type="button" class="btn btn-primary">
            <%= link_to 'Sign Up', new_user_registration_path %>
        </button>

    <% elsif user_signed_in? && !@portfolio.exists? %>  
        <p>Sorry! You do not have any photos in your portfolio.</p>
        <p>Please click the button below to start adding photos to your portfolio.</p>
        <button type="button" class="btn btn-primary">
            <%= link_to 'Upload a New Photo', new_photo_path %>
        </button>

    <% else %>  
        <section class="main">
            <% @portfolio.each do | photo | %> 
            <div class="card" style="width: 18rem;">
                <%= image_tag photo.image, class: "card-img-top" %>
                
                <div class="card-body">
                    <strong>Title: </strong><%= sanitize(photo.title) %>
                    <br>
                    <% if photo.category? %>
                    <strong>Category: </strong><%= photo.category %>
                    <% else %>
                    <&nbsp;;>
                    <% end %>
                    <br>
                    <strong>Price: $</strong><%= photo.price %>
                    <br>

                <button type="button" class="btn btn-primary">
                    <%= link_to 'View Details', photo %>
                </button>

                <% if photo.user_id == current_user.id %>
                    <button type="button" class="btn btn-primary">
                    <%= link_to 'Edit', edit_photo_path(photo) %>
                    </button>

                    <button type="button" class="btn btn-primary">
                        <%= link_to 'Delete', photo, method: :delete, data: { confirm: 'Are you sure? This action is permanent.' } %>
                    </button>
                    </div>
                <% end %>
                </div>
        
            </div>
            <% end %>

        </div>
        </section>
    <% end %>

app/views/photos/show.html.erb
<section class="show_page">
  <main>
  <p id="notice"><%= notice %></p>

  <h1>
    <%= sanitize(@photo.title) %>
  </h1>

  <p>
    <%= image_tag @photo.image %>
  </p> 

  <p>
    <strong>Description:</strong>
    <%= sanitize(@photo.description) %>
  </p>

  <p>
    <strong>Price: $</strong>
    <%= @photo.price %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @photo.category %>
  </p>

  <p>
    <strong>Style:</strong>
    <%= @photo.style %>
  </p>

  <p>
    <strong>Date Added:</strong>
    <%= @photo.created_at.strftime("%d/%m/%Y") %>
  </p>

  <br>

 <% if user_signed_in? %>
    <button type="button" id="checkout-button" class="btn btn-info">Buy Now</button>
  <% else %>
    <button type="button" class="btn btn-info">
      <%= link_to 'Log In to Buy', new_user_session_path %>
    </button>
<% end %>

  <% if user_signed_in? %>
    <% if @photo.user_id == current_user.id %>
      <button type="button" class="btn btn-info">
        <%= link_to 'Edit', edit_photo_path(@photo) %>
      </button>
    <% end %>
  <% end %>

  <button type="button" class="btn btn-info">
    <%= link_to 'Back', photos_path %>
  </button>

  <br>
</section>

<%# Stripe checkout button %>
<script type="text/javascript">
  // Create an instance of the Stripe object with your publishable API key
  var stripe = Stripe("<%= Rails.application.credentials.dig(:stripe, :public_key) %>");

  var checkoutButton = document.getElementById("checkout-button");
  checkoutButton.addEventListener("click", function () {
    fetch("/transactions", {
      method: "POST",
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
      },
      body: "id=<%= @photo.id %>"
    })
      .then(function (response) {
        return response.json();
      })
      .then(function (session) {
        return stripe.redirectToCheckout({ sessionId: session.id });
      })
      .then(function (result) {
        // If redirectToCheckout fails due to a browser or network
        // error, you should display the localized error message to your
        // customer using error.message.
        if (result.error) {
          alert(result.error.message);
        }
      })
      .catch(function (error) {
        console.error("Error:", error);
      });
  });
</script>

</main>

app/views/shared/_header.html.erb
<header id="top">
    <div class="header_image">
        <%= image_tag "neon_camera_30cm.png" %>
    </div>

    <div class="header_text">
        <h1>Pixeltastic</h1>
    </div>
</header>

<br>

<section class="log_status">
    <% if user_signed_in? %>
        <p>Currently signed in as:&nbsp;</p><%= current_user.email %>
    <% else %>
        <p>You are currently visiting as a guest.</p>
    <% end %>
</section>

app/views/shared/_navbar.html.erb
<nav>
  <button type="button" class="btn btn-primary">
      <%= link_to 'Home', home_page_path %>
  </button>

  <button type="button" class="btn btn-primary">
      <%= link_to 'View Image Catalogue', photos_path %>
  </button>

  <button type="button" class="btn btn-primary">
      <%= link_to 'My Portfolio', portfolio_path %>
  </button>

  <button type="button" class="btn btn-primary">
      <%= link_to 'Upload a New Photo', new_photo_path %>
  </button>

    <% if user_signed_in? %>
        <button type="button" class="btn btn-primary">
            <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
        </button>
    <% end %>

    <% if !user_signed_in? %>
        <button type="button" class="btn btn-primary">
            <%= link_to 'Log In', new_user_session_path %>
        </button>
    <% end %>  

    <% if !user_signed_in? %>
        <button type="button" class="btn btn-primary">
            <%= link_to 'Sign Up', new_user_registration_path %>
        </button>
    <% end %> 

  <button type="button" class="btn btn-primary">
      <a href="#top">Top of Page</a>
  </button>

  <button type="button" class="btn btn-primary">
      <%= link_to 'Help', home_help_path %>
  </button>

</nav>

app/views/transactions/success.html.erb
<h1>Success!</h1>
<p>Thank you. Your payment has been successfully processed. Please click on the link below to download the photo you have purchased.</p>